ASSUME CS:CODE, DS:DATA
DATA SEGMENT
ARRAY DB 01H,02H,03H,04H,05H,06H,07H,08H,09H,10H
ODD DB ?
DATA ENDS
CODE SEGMENT
START:MOV AX,DATA
    MOV DS,AX
    LEA SI,ARRAY
    MOV DI,2000H
    MOV CX,0005H
    XOR AX,AX
    XOR DX,DX
    MOV BL,02H
    MOV BH,00H
    LOOP1:MOV AL,[SI]
        DIV BL
        CMP AH,00H
        JE NEXT
        ADD DL,[SI]
        INC BH
        NEXT:INC SI
            DEC CL
            JNZ LOOP1
    MOV [DI],DX
    INC DI
    INC DI
    MOV AX,DX
    DIV BH
    MOV [DI],AX
    INT 3
CODE ENDS
END START
